### ISSUE TITLE
Need publishing

### ISSUE THREAD

**Issue by brettviren** [WireCell/wire-cell-tutorial#1]
I set the URLs I could find from czczc to wirecell github org.  Someone that knows how "vuepress" works, please run deploy.sh.

**Comment by HaiwangYu** [comment]
Seems working:
https://wirecell.github.io/wire-cell-tutorial/develop/style-guide.html

**Comment by brettviren** [comment]
Huh.  I could have sworn it gave a 404.  Thanks!
